# Generated by Django 5.0.6 on 2024-06-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="заголовок")),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("content", models.TextField(verbose_name="содержимое")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="изображение"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="опубликовано"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="просмотры"),
                ),
            ],
            options={
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
            },
        ),
        migrations.DeleteModel(
            name="BlogPost",
        ),
    ]
