# Generated by Django 5.0.6 on 2024-06-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=150,
                null=True,
                upload_to="",
                verbose_name="Изображение",
            ),
        ),
    ]
